import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Mera Blog!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <style jsx>
        {`
        h2{
          font-size: 40px;
          width: fit-content;
          margin: auto;
          margin-bottom: 20px; 
        }
        h3{
          font-size: 25px;
          margin-top: 10px;
        }
        `}
      </style>

      <main className={styles.main}>

        <div className={styles.center}>
          <h1 style={{ fontFamily: "Poppins", fontSize: "56px" }}>Mera Blog</h1>

        </div>
        <div className={styles.imgBox}>
          <Image src='/table.jpg' width={270} height={180} />
          {/* We Cannot Use <Image/> element if we want to create a static site. */}
          {/* <img src='/table.jpg' width={450} height={300} /> */}
        </div>

        <div className={styles.blogs}>
          <h2>Popular Blogs</h2>
          <div className={styles.grid}>
            <div className={styles.card}>
              <h3>How to learn Javascript in 2023</h3>
              <p>Javascript is the language used for designing languages for web</p>
            </div>
            <div className={styles.card}>
              <h3>How to learn Javascript in 2023</h3>
              <p>Javascript is the language used for designing languages for web</p>
            </div>
            <div className={styles.card}>
              <h3>How to learn Javascript in 2023</h3>
              <p>Javascript is the language used for designing languages for web</p>
            </div>
            <div className={styles.card}>
              <h3>How to learn Javascript in 2023</h3>
              <p>Javascript is the language used for designing languages for web</p>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
